#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsigc++
Version  : 3.0.3
Release  : 13
URL      : https://download.gnome.org/sources/libsigc++/3.0/libsigc++-3.0.3.tar.xz
Source0  : https://download.gnome.org/sources/libsigc++/3.0/libsigc++-3.0.3.tar.xz
Summary  : Typesafe signal and callback system for C++
Group    : Development/Tools
License  : LGPL-3.0
Requires: libsigc++-data = %{version}-%{release}
Requires: libsigc++-lib = %{version}-%{release}
Requires: libsigc++-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson

%description


%package data
Summary: data components for the libsigc++ package.
Group: Data

%description data
data components for the libsigc++ package.


%package dev
Summary: dev components for the libsigc++ package.
Group: Development
Requires: libsigc++-lib = %{version}-%{release}
Requires: libsigc++-data = %{version}-%{release}
Provides: libsigc++-devel = %{version}-%{release}
Requires: libsigc++ = %{version}-%{release}

%description dev
dev components for the libsigc++ package.


%package doc
Summary: doc components for the libsigc++ package.
Group: Documentation

%description doc
doc components for the libsigc++ package.


%package lib
Summary: lib components for the libsigc++ package.
Group: Libraries
Requires: libsigc++-data = %{version}-%{release}
Requires: libsigc++-license = %{version}-%{release}

%description lib
lib components for the libsigc++ package.


%package license
Summary: license components for the libsigc++ package.
Group: Default

%description license
license components for the libsigc++ package.


%prep
%setup -q -n libsigc++-3.0.3
cd %{_builddir}/libsigc++-3.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585853391
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1585853391
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libsigc++
cp %{_builddir}/libsigc++-3.0.3/COPYING %{buildroot}/usr/share/package-licenses/libsigc++/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait_3_01T__type[N]_4-members.html
rm -f %{buildroot}/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait_3_01T__type[N]_4.html
## install_append content
rm %{buildroot}/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1type__trait_3_01T__type*

## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/devhelp/books/libsigc++-3.0/libsigc++-3.0.devhelp2

%files dev
%defattr(-,root,root,-)
/usr/include/sigc++-3.0/sigc++/adaptors/adaptor_base.h
/usr/include/sigc++-3.0/sigc++/adaptors/adaptor_trait.h
/usr/include/sigc++-3.0/sigc++/adaptors/adaptors.h
/usr/include/sigc++-3.0/sigc++/adaptors/adapts.h
/usr/include/sigc++-3.0/sigc++/adaptors/bind.h
/usr/include/sigc++-3.0/sigc++/adaptors/bind_return.h
/usr/include/sigc++-3.0/sigc++/adaptors/bound_argument.h
/usr/include/sigc++-3.0/sigc++/adaptors/compose.h
/usr/include/sigc++-3.0/sigc++/adaptors/exception_catch.h
/usr/include/sigc++-3.0/sigc++/adaptors/hide.h
/usr/include/sigc++-3.0/sigc++/adaptors/retype.h
/usr/include/sigc++-3.0/sigc++/adaptors/retype_return.h
/usr/include/sigc++-3.0/sigc++/adaptors/track_obj.h
/usr/include/sigc++-3.0/sigc++/adaptors/tuple_visitor_visit_each.h
/usr/include/sigc++-3.0/sigc++/bind.h
/usr/include/sigc++-3.0/sigc++/bind_return.h
/usr/include/sigc++-3.0/sigc++/connection.h
/usr/include/sigc++-3.0/sigc++/functors/functor_trait.h
/usr/include/sigc++-3.0/sigc++/functors/functors.h
/usr/include/sigc++-3.0/sigc++/functors/mem_fun.h
/usr/include/sigc++-3.0/sigc++/functors/ptr_fun.h
/usr/include/sigc++-3.0/sigc++/functors/slot.h
/usr/include/sigc++-3.0/sigc++/functors/slot_base.h
/usr/include/sigc++-3.0/sigc++/limit_reference.h
/usr/include/sigc++-3.0/sigc++/member_method_trait.h
/usr/include/sigc++-3.0/sigc++/reference_wrapper.h
/usr/include/sigc++-3.0/sigc++/retype_return.h
/usr/include/sigc++-3.0/sigc++/sigc++.h
/usr/include/sigc++-3.0/sigc++/signal.h
/usr/include/sigc++-3.0/sigc++/signal_base.h
/usr/include/sigc++-3.0/sigc++/slot.h
/usr/include/sigc++-3.0/sigc++/trackable.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_cdr.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_end.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_for_each.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_start.h
/usr/include/sigc++-3.0/sigc++/tuple-utils/tuple_transform_each.h
/usr/include/sigc++-3.0/sigc++/type_traits.h
/usr/include/sigc++-3.0/sigc++/visit_each.h
/usr/include/sigc++-3.0/sigc++/weak_raw_ptr.h
/usr/lib64/libsigc-3.0.so
/usr/lib64/pkgconfig/sigc++-3.0.pc
/usr/lib64/sigc++-3.0/include/sigc++config.h

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libsigc++-3.0/reference/html/annotated.html
/usr/share/doc/libsigc++-3.0/reference/html/arrowdown.png
/usr/share/doc/libsigc++-3.0/reference/html/arrowright.png
/usr/share/doc/libsigc++-3.0/reference/html/bc_s.png
/usr/share/doc/libsigc++-3.0/reference/html/bdwn.png
/usr/share/doc/libsigc++-3.0/reference/html/classes.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__argument-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__argument.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__argument_3_01std_1_1reference__wrapper_3_01T__wrapped_01_4_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__argument_3_01std_1_1reference__wrapper_3_01T__wrapped_01_4_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__argument_3_01std_1_1reference__wrapper_3_01const_01T__wrapped_01_4_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__mem__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__mem__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1bound__mem__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1limit__reference-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1limit__reference.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1limit__reference_3_01T__type_00_01true_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1limit__reference_3_01T__type_00_01true_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1mem__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1mem__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1pointer__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1pointer__functor_3_01T__return_07T__args_8_8_8_08_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1pointer__functor_3_01T__return_07T__args_8_8_8_08_4.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg_8_8_8_08_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg_8_8_8_08_4.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg_8_8_8_08_4_1_1accumulated-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg_8_8_8_08_4_1_1accumulated.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg_8_8_8_08_4_1_1accumulated__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg_8_8_8_08_4__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal__with__accumulator-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal__with__accumulator.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1signal__with__accumulator__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1slot_3_01T__return_07T__arg_8_8_8_08_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1slot_3_01T__return_07T__arg_8_8_8_08_4.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1slot_3_01T__return_07T__arg_8_8_8_08_4__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1slot__base-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1slot__base.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1slot__base__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1track__obj__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1track__obj__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/classsigc_1_1track__obj__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/closed.png
/usr/share/doc/libsigc++-3.0/reference/html/dir_0bd3c8d814eb03171de012519d7a2ccd.html
/usr/share/doc/libsigc++-3.0/reference/html/dir_5c02128c554eaa40138b2e605fc08970.html
/usr/share/doc/libsigc++-3.0/reference/html/dir_5fbc72877197f8c6013d0f619df5433c.html
/usr/share/doc/libsigc++-3.0/reference/html/dir_721a6b9909c6844e1177e3a6a712a0d2.html
/usr/share/doc/libsigc++-3.0/reference/html/doc.png
/usr/share/doc/libsigc++-3.0/reference/html/doxygen-extra.css
/usr/share/doc/libsigc++-3.0/reference/html/doxygen.css
/usr/share/doc/libsigc++-3.0/reference/html/doxygen.png
/usr/share/doc/libsigc++-3.0/reference/html/dynsections.js
/usr/share/doc/libsigc++-3.0/reference/html/folderclosed.png
/usr/share/doc/libsigc++-3.0/reference/html/folderopen.png
/usr/share/doc/libsigc++-3.0/reference/html/functions.html
/usr/share/doc/libsigc++-3.0/reference/html/functions_func.html
/usr/share/doc/libsigc++-3.0/reference/html/functions_type.html
/usr/share/doc/libsigc++-3.0/reference/html/functions_vars.html
/usr/share/doc/libsigc++-3.0/reference/html/graph_legend.html
/usr/share/doc/libsigc++-3.0/reference/html/graph_legend.png
/usr/share/doc/libsigc++-3.0/reference/html/group__adaptors.html
/usr/share/doc/libsigc++-3.0/reference/html/group__bind.html
/usr/share/doc/libsigc++-3.0/reference/html/group__compose.html
/usr/share/doc/libsigc++-3.0/reference/html/group__exception__catch.html
/usr/share/doc/libsigc++-3.0/reference/html/group__hide.html
/usr/share/doc/libsigc++-3.0/reference/html/group__mem__fun.html
/usr/share/doc/libsigc++-3.0/reference/html/group__ptr__fun.html
/usr/share/doc/libsigc++-3.0/reference/html/group__retype.html
/usr/share/doc/libsigc++-3.0/reference/html/group__sigcfunctors.html
/usr/share/doc/libsigc++-3.0/reference/html/group__signal.html
/usr/share/doc/libsigc++-3.0/reference/html/group__slot.html
/usr/share/doc/libsigc++-3.0/reference/html/group__track__obj.html
/usr/share/doc/libsigc++-3.0/reference/html/hierarchy.html
/usr/share/doc/libsigc++-3.0/reference/html/index.html
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_0.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_1.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_10.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_11.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_12.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_13.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_14.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_15.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_16.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_17.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_18.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_19.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_2.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_20.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_21.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_22.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_23.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_24.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_25.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_26.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_27.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_28.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_29.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_3.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_30.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_31.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_4.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_5.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_6.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_7.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_8.png
/usr/share/doc/libsigc++-3.0/reference/html/inherit_graph_9.png
/usr/share/doc/libsigc++-3.0/reference/html/inherits.html
/usr/share/doc/libsigc++-3.0/reference/html/jquery.js
/usr/share/doc/libsigc++-3.0/reference/html/modules.html
/usr/share/doc/libsigc++-3.0/reference/html/namespacemembers.html
/usr/share/doc/libsigc++-3.0/reference/html/namespacemembers_func.html
/usr/share/doc/libsigc++-3.0/reference/html/namespacemembers_type.html
/usr/share/doc/libsigc++-3.0/reference/html/namespaces.html
/usr/share/doc/libsigc++-3.0/reference/html/namespacesigc.html
/usr/share/doc/libsigc++-3.0/reference/html/nav_f.png
/usr/share/doc/libsigc++-3.0/reference/html/nav_g.png
/usr/share/doc/libsigc++-3.0/reference/html/nav_h.png
/usr/share/doc/libsigc++-3.0/reference/html/open.png
/usr/share/doc/libsigc++-3.0/reference/html/pages.html
/usr/share/doc/libsigc++-3.0/reference/html/since_2_4.html
/usr/share/doc/libsigc++-3.0/reference/html/since_2_8.html
/usr/share/doc/libsigc++-3.0/reference/html/splitbar.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__base.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__base__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__trait.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01false_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01false_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01true_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01true_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adapts-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adapts.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1adapts__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__functor_3-1_00_01T__functor_00_01T__type_8_8_8_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__functor_3-1_00_01T__functor_00_01T__type_8_8_8_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__functor_3-1_00_01T__functor_00_01T__type_8_8_8_01_4__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__return__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__return__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1bind__return__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1compose1__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1compose1__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1compose1__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1compose2__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1compose2__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1compose2__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1connection-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1connection.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1exception__catch__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1exception__catch__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1exception__catch__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1functor__trait-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1functor__trait.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1hide__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1hide__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1hide__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1notifiable-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1notifiable.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1notifiable__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__return__functor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__return__functor.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1retype__return__functor__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1signal__base-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1signal__base.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1signal__base__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1trackable-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1trackable.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1trackable__inherit__graph.png
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1type__trait-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1type__trait.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1type__trait_3_01const_01T__type_01_6_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1type__trait_3_01const_01T__type_01_6_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1type__trait_3_01void_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1type__trait_3_01void_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1unwrap__reference-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1unwrap__reference.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1unwrap__reference_3_01std_1_1reference__wrapper_3_01T__type_01_4_01_4-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1unwrap__reference_3_01std_1_1reference__wrapper_3_01T__type_01_4_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1unwrap__reference_3_01std_1_1reference__wrapper_3_01const_01T__type_01_4_01_4.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1visitor-members.html
/usr/share/doc/libsigc++-3.0/reference/html/structsigc_1_1visitor.html
/usr/share/doc/libsigc++-3.0/reference/html/sync_off.png
/usr/share/doc/libsigc++-3.0/reference/html/sync_on.png
/usr/share/doc/libsigc++-3.0/reference/html/tab_a.png
/usr/share/doc/libsigc++-3.0/reference/html/tab_b.png
/usr/share/doc/libsigc++-3.0/reference/html/tab_h.png
/usr/share/doc/libsigc++-3.0/reference/html/tab_s.png
/usr/share/doc/libsigc++-3.0/reference/html/tabs.css
/usr/share/doc/libsigc++-3.0/reference/libsigc++-3.0.tag
/usr/share/doc/libsigc++-3.0/tutorial/html/ch01.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch02.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch02s02.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch02s03.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch02s04.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch03.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch03s02.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch04.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch04s02.html
/usr/share/doc/libsigc++-3.0/tutorial/html/ch05.html
/usr/share/doc/libsigc++-3.0/tutorial/html/index.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsigc-3.0.so.0
/usr/lib64/libsigc-3.0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsigc++/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c
