#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsigc++
Version  : 2.10.2
Release  : 14
URL      : https://download.gnome.org/sources/libsigc++/2.10/libsigc++-2.10.2.tar.xz
Source0  : https://download.gnome.org/sources/libsigc++/2.10/libsigc++-2.10.2.tar.xz
Summary  : Typesafe signal and callback system for C++
Group    : Development/Tools
License  : LGPL-2.1
Requires: libsigc++-data = %{version}-%{release}
Requires: libsigc++-lib = %{version}-%{release}
Requires: libsigc++-license = %{version}-%{release}
BuildRequires : buildreq-gnome

%description
libsigc++ -- The Typesafe Callback Framework for C++
General information:
libsigc++ implements a typesafe callback system for standard C++. It
allows you to define signals and to connect those signals to any
callback function, either global or a member function, regardless of
whether it is static or virtual.

%package data
Summary: data components for the libsigc++ package.
Group: Data

%description data
data components for the libsigc++ package.


%package dev
Summary: dev components for the libsigc++ package.
Group: Development
Requires: libsigc++-lib = %{version}-%{release}
Requires: libsigc++-data = %{version}-%{release}
Provides: libsigc++-devel = %{version}-%{release}
Requires: libsigc++ = %{version}-%{release}

%description dev
dev components for the libsigc++ package.


%package doc
Summary: doc components for the libsigc++ package.
Group: Documentation

%description doc
doc components for the libsigc++ package.


%package lib
Summary: lib components for the libsigc++ package.
Group: Libraries
Requires: libsigc++-data = %{version}-%{release}
Requires: libsigc++-license = %{version}-%{release}

%description lib
lib components for the libsigc++ package.


%package license
Summary: license components for the libsigc++ package.
Group: Default

%description license
license components for the libsigc++ package.


%prep
%setup -q -n libsigc++-2.10.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562611351
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1562611351
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libsigc++
cp COPYING %{buildroot}/usr/share/package-licenses/libsigc++/COPYING
%make_install
## install_append content
rm %{buildroot}/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait_3_01T__type*
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/devhelp/books/libsigc++-2.0/libsigc++-2.0.devhelp2

%files dev
%defattr(-,root,root,-)
/usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h
/usr/include/sigc++-2.0/sigc++/adaptors/adaptors.h
/usr/include/sigc++-2.0/sigc++/adaptors/bind.h
/usr/include/sigc++-2.0/sigc++/adaptors/bind_return.h
/usr/include/sigc++-2.0/sigc++/adaptors/bound_argument.h
/usr/include/sigc++-2.0/sigc++/adaptors/compose.h
/usr/include/sigc++-2.0/sigc++/adaptors/deduce_result_type.h
/usr/include/sigc++-2.0/sigc++/adaptors/exception_catch.h
/usr/include/sigc++-2.0/sigc++/adaptors/hide.h
/usr/include/sigc++-2.0/sigc++/adaptors/lambda/base.h
/usr/include/sigc++-2.0/sigc++/adaptors/lambda/select.h
/usr/include/sigc++-2.0/sigc++/adaptors/retype.h
/usr/include/sigc++-2.0/sigc++/adaptors/retype_return.h
/usr/include/sigc++-2.0/sigc++/adaptors/track_obj.h
/usr/include/sigc++-2.0/sigc++/bind.h
/usr/include/sigc++-2.0/sigc++/bind_return.h
/usr/include/sigc++-2.0/sigc++/connection.h
/usr/include/sigc++-2.0/sigc++/functors/functor_trait.h
/usr/include/sigc++-2.0/sigc++/functors/functors.h
/usr/include/sigc++-2.0/sigc++/functors/mem_fun.h
/usr/include/sigc++-2.0/sigc++/functors/ptr_fun.h
/usr/include/sigc++-2.0/sigc++/functors/slot.h
/usr/include/sigc++-2.0/sigc++/functors/slot_base.h
/usr/include/sigc++-2.0/sigc++/limit_reference.h
/usr/include/sigc++-2.0/sigc++/reference_wrapper.h
/usr/include/sigc++-2.0/sigc++/retype_return.h
/usr/include/sigc++-2.0/sigc++/sigc++.h
/usr/include/sigc++-2.0/sigc++/signal.h
/usr/include/sigc++-2.0/sigc++/signal_base.h
/usr/include/sigc++-2.0/sigc++/slot.h
/usr/include/sigc++-2.0/sigc++/trackable.h
/usr/include/sigc++-2.0/sigc++/type_traits.h
/usr/include/sigc++-2.0/sigc++/visit_each.h
/usr/lib64/libsigc-2.0.so
/usr/lib64/pkgconfig/sigc++-2.0.pc
/usr/lib64/sigc++-2.0/include/sigc++config.h

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libsigc++-2.0/images/libsigc_logo.gif
/usr/share/doc/libsigc++-2.0/images/top.gif
/usr/share/doc/libsigc++-2.0/index.html
/usr/share/doc/libsigc++-2.0/reference/html/annotated.html
/usr/share/doc/libsigc++-2.0/reference/html/arrowdown.png
/usr/share/doc/libsigc++-2.0/reference/html/arrowright.png
/usr/share/doc/libsigc++-2.0/reference/html/bc_s.png
/usr/share/doc/libsigc++-2.0/reference/html/bdwn.png
/usr/share/doc/libsigc++-2.0/reference/html/classes.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument_3_01const__reference__wrapper_3_01T__wrapped_01_4_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument_3_01const__reference__wrapper_3_01T__wrapped_01_4_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument_3_01reference__wrapper_3_01T__wrapped_01_4_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument_3_01reference__wrapper_3_01T__wrapped_01_4_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument_3_01std_1_1reference__wrapper_3_01T__wrapped_01_4_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__argument_3_01std_1_1reference__wrapper_3_01T__wrapped_01_4_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__const__volatile__mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1bound__volatile__mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1can__deduce__result__type__with__decltype-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1can__deduce__result__type__with__decltype.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__limit__reference-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__limit__reference.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__limit__reference_3_01T__type_00_01true_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__limit__reference_3_01T__type_00_01true_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__limit__reference-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__limit__reference.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__limit__reference_3_01T__type_00_01true_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__limit__reference_3_01T__type_00_01true_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1const__volatile__mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1limit__reference-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1limit__reference.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1limit__reference_3_01T__type_00_01true_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1limit__reference_3_01T__type_00_01true_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1pointer__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_1_1accumulated-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_1_1accumulated.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_1_1accumulated__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_08_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_00_01T__arg4_08_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_08_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_08_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_08_4_1_1accumulated.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_00_01T__arg3_08_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_08_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_08_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_08_4_1_1accumulated-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_08_4_1_1accumulated.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_08_4_1_1accumulated__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_00_01T__arg2_08_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_08_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_08_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_08_4_1_1accumulated-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_08_4_1_1accumulated.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_08_4_1_1accumulated__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07T__arg1_08_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07_08_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07_08_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07_08_4_1_1accumulated-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07_08_4_1_1accumulated.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07_08_4_1_1accumulated__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal_3_01T__return_07_08_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1signal__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot_3_01T__return_07T__arg_8_8_8_08_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot_3_01T__return_07T__arg_8_8_8_08_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot_3_01T__return_07T__arg_8_8_8_08_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot__base-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot__base.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot__base__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1slot__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1track__obj__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__limit__reference-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__limit__reference.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__limit__reference_3_01T__type_00_01true_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__limit__reference_3_01T__type_00_01true_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor0-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor0.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor0__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor1-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor1.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor1__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor2-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor2.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor2__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor3-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor3.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor3__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor4.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor5-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor5.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor5__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor6-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor6.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor6__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor7-members.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor7.html
/usr/share/doc/libsigc++-2.0/reference/html/classsigc_1_1volatile__mem__functor7__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/closed.png
/usr/share/doc/libsigc++-2.0/reference/html/deprecated.html
/usr/share/doc/libsigc++-2.0/reference/html/dir_69292b900bf9f32fa1522c0a297aa561.html
/usr/share/doc/libsigc++-2.0/reference/html/dir_7061c03125b177af05ebe54a01c7815e.html
/usr/share/doc/libsigc++-2.0/reference/html/dir_a7a614a8e549e28882ee9909ca095aec.html
/usr/share/doc/libsigc++-2.0/reference/html/dir_d1b074183e01b19b1ce0df6f4868a06f.html
/usr/share/doc/libsigc++-2.0/reference/html/dir_e610d0fd7d8d422b14c5e759f0ef71be.html
/usr/share/doc/libsigc++-2.0/reference/html/dir_e7ee533ee50f0002bd12390b80ea971b.html
/usr/share/doc/libsigc++-2.0/reference/html/dir_ffa8fd617c28221f63108bd7d58d97eb.html
/usr/share/doc/libsigc++-2.0/reference/html/doc.png
/usr/share/doc/libsigc++-2.0/reference/html/doxygen-extra.css
/usr/share/doc/libsigc++-2.0/reference/html/doxygen.css
/usr/share/doc/libsigc++-2.0/reference/html/doxygen.png
/usr/share/doc/libsigc++-2.0/reference/html/dynsections.js
/usr/share/doc/libsigc++-2.0/reference/html/folderclosed.png
/usr/share/doc/libsigc++-2.0/reference/html/folderopen.png
/usr/share/doc/libsigc++-2.0/reference/html/functions.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_0x7e.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_b.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_c.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_d.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_e.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_f.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_0x7e.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_b.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_c.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_d.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_e.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_f.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_h.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_i.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_l.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_m.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_n.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_o.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_p.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_r.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_s.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_t.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_u.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_func_v.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_g.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_h.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_i.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_l.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_m.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_n.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_o.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_p.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_r.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_s.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_t.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_c.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_d.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_e.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_f.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_g.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_i.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_p.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_r.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_s.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_t.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_type_v.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_u.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_v.html
/usr/share/doc/libsigc++-2.0/reference/html/functions_vars.html
/usr/share/doc/libsigc++-2.0/reference/html/graph_legend.html
/usr/share/doc/libsigc++-2.0/reference/html/graph_legend.png
/usr/share/doc/libsigc++-2.0/reference/html/group__adaptors.html
/usr/share/doc/libsigc++-2.0/reference/html/group__bind.html
/usr/share/doc/libsigc++-2.0/reference/html/group__compose.html
/usr/share/doc/libsigc++-2.0/reference/html/group__exception__catch.html
/usr/share/doc/libsigc++-2.0/reference/html/group__hide.html
/usr/share/doc/libsigc++-2.0/reference/html/group__mem__fun.html
/usr/share/doc/libsigc++-2.0/reference/html/group__ptr__fun.html
/usr/share/doc/libsigc++-2.0/reference/html/group__retype.html
/usr/share/doc/libsigc++-2.0/reference/html/group__sigcfunctors.html
/usr/share/doc/libsigc++-2.0/reference/html/group__signal.html
/usr/share/doc/libsigc++-2.0/reference/html/group__slot.html
/usr/share/doc/libsigc++-2.0/reference/html/group__track__obj.html
/usr/share/doc/libsigc++-2.0/reference/html/hierarchy.html
/usr/share/doc/libsigc++-2.0/reference/html/index.html
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_0.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_1.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_10.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_11.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_12.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_13.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_14.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_15.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_16.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_17.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_18.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_19.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_2.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_20.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_21.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_22.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_23.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_24.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_25.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_26.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_27.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_28.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_29.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_3.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_30.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_31.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_32.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_33.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_34.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_35.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_36.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_37.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_38.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_39.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_4.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_40.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_41.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_42.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_43.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_44.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_45.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_46.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_47.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_48.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_49.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_5.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_6.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_7.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_8.png
/usr/share/doc/libsigc++-2.0/reference/html/inherit_graph_9.png
/usr/share/doc/libsigc++-2.0/reference/html/inherits.html
/usr/share/doc/libsigc++-2.0/reference/html/jquery.js
/usr/share/doc/libsigc++-2.0/reference/html/modules.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_c.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_d.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_e.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_c.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_e.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_h.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_m.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_p.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_r.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_t.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_u.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_func_v.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_h.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_m.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_p.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_r.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_t.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_type.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_u.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacemembers_v.html
/usr/share/doc/libsigc++-2.0/reference/html/namespaces.html
/usr/share/doc/libsigc++-2.0/reference/html/namespacesigc.html
/usr/share/doc/libsigc++-2.0/reference/html/nav_f.png
/usr/share/doc/libsigc++-2.0/reference/html/nav_g.png
/usr/share/doc/libsigc++-2.0/reference/html/nav_h.png
/usr/share/doc/libsigc++-2.0/reference/html/open.png
/usr/share/doc/libsigc++-2.0/reference/html/pages.html
/usr/share/doc/libsigc++-2.0/reference/html/since_2_2_11.html
/usr/share/doc/libsigc++-2.0/reference/html/since_2_4.html
/usr/share/doc/libsigc++-2.0/reference/html/since_2_8.html
/usr/share/doc/libsigc++-2.0/reference/html/splitbar.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__base.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__base__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__functor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__functor__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__trait.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01false_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01false_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01true_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adaptor__trait_3_01T__functor_00_01true_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adapts-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adapts.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1adapts__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1bind__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1bind__return__functor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1bind__return__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1bind__return__functor__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1compose1__functor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1compose1__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1compose1__functor__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1compose2__functor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1compose2__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1compose2__functor__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1connection-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1connection.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1const__reference__wrapper-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1const__reference__wrapper.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1deduce__result__type-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1deduce__result__type.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1exception__catch__functor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1exception__catch__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1exception__catch__functor_3_01T__functor_00_01T__catcher_00_01void_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1exception__catch__functor_3_01T__functor_00_01T__catcher_00_01void_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1exception__catch__functor__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1functor__base.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1functor__base__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1functor__trait-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1functor__trait.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1hide__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1hide__functor_3-1_00_01T__functor_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1hide__functor_3-1_00_01T__functor_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1hide__functor_3-1_00_01T__functor_01_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1hide__functor_3_010_00_01T__functor_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1hide__functor_3_010_00_01T__functor_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1hide__functor_3_010_00_01T__functor_01_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1nil.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1reference__wrapper-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1reference__wrapper.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__functor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__functor__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__return__functor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__return__functor.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__return__functor_3_01void_00_01T__functor_01_4__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1retype__return__functor__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1signal__base-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1signal__base.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1signal__base__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1slot__const__iterator-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1slot__const__iterator.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1slot__iterator-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1slot__iterator.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1slot__list-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1slot__list.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1trackable-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1trackable.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1trackable__inherit__graph.png
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait_3_01const_01T__type_01_6_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait_3_01const_01T__type_01_6_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait_3_01void_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1type__trait_3_01void_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference_3_01const__reference__wrapper_3_01T__type_01_4_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference_3_01const__reference__wrapper_3_01T__type_01_4_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference_3_01reference__wrapper_3_01T__type_01_4_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference_3_01reference__wrapper_3_01T__type_01_4_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference_3_01std_1_1reference__wrapper_3_01T__type_01_4_01_4-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1unwrap__reference_3_01std_1_1reference__wrapper_3_01T__type_01_4_01_4.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1visitor-members.html
/usr/share/doc/libsigc++-2.0/reference/html/structsigc_1_1visitor.html
/usr/share/doc/libsigc++-2.0/reference/html/sync_off.png
/usr/share/doc/libsigc++-2.0/reference/html/sync_on.png
/usr/share/doc/libsigc++-2.0/reference/html/tab_a.png
/usr/share/doc/libsigc++-2.0/reference/html/tab_b.png
/usr/share/doc/libsigc++-2.0/reference/html/tab_h.png
/usr/share/doc/libsigc++-2.0/reference/html/tab_s.png
/usr/share/doc/libsigc++-2.0/reference/html/tabs.css
/usr/share/doc/libsigc++-2.0/reference/libsigc++-2.0.tag
/usr/share/doc/libsigc++-2.0/tutorial/html/ch01.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch02.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch02s02.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch02s03.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch02s04.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch03.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch03s02.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch04.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch04s02.html
/usr/share/doc/libsigc++-2.0/tutorial/html/ch05.html
/usr/share/doc/libsigc++-2.0/tutorial/html/index.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsigc-2.0.so.0
/usr/lib64/libsigc-2.0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsigc++/COPYING
